defaults:
  theme: catppuccin-macchiato
snippet:
  exec:
    enable: true
  exec_replace:
    enable: true
options:
  auto_render_languages:
    - d2
    - mermaid
    - latex
  command_prefix: "cmd:"
  strict_front_matter_parsing: false
