services:
  tsdproxy:
    container_name: tsdproxy
    image: almeidapaulopt/tsdproxy:1
    restart: unless-stopped
    ports:
      - 8080
    volumes:
      - /home/c4patino/dotfiles/inputs/dotfiles/tsdproxy:/config
      - tsdproxy:/data
      - /var/run/docker.sock:/var/run/docker.sock
      - /run/secrets/tailscale/tsdproxy:/run/secrets/tailscale/tsdproxy

volumes:
  tsdproxy:
