services:
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    ports: 
      - 8096
    labels:
      tsdproxy.enable: true
      tsdproxy.funnel: true
    volumes:
      - jellyfin-config:/config
      - jellyfin-cache:/cache
      - jellyfin-media:/media

volumes:
  jellyfin-config:
  jellyfin-cache:
  jellyfin-media:

