"$schema" = "https://starship.rs/config-schema.json"

format = '''
[╭─](text)$os[─](text)$directory[─](text)$git_branch$git_commit$git_status$fill$nodejs$bun$deno$c$cpp$cmake$java$gradle$dotnet$haskell$lua$python$rust$conda$nix_shell$direnv[─](text)[\[](text)$username[@](blue)$hostname[\]](text)[─](text)$time$battery
[╰─](text)$cmd_duration $character
'''

add_newline = false
palette = "tokyonight_night"

command_timeout = 2500

[aws]
disabled = true
format = '([\[](text)[$symbol($profile)(\($region\))(\[$duration[\]](text))]($style)\])'
symbol = " "

[azure]
disabled = true
symbol = " "

[battery]
charging_symbol = "󰂄 "
discharging_symbol = "󰂃 "
empty_symbol = "󰂎 "
format = '([─\[](text)[$symbol$percentage]($style)[\]](text))'
full_symbol = "󰁹 "
unknown_symbol = "󰁽 "

[[battery.display]]
style = "bold red"
threshold = 10

[[battery.display]]
style = "bold yellow"
threshold = 30

[buf]
symbol = " "

[bun]
format = '([\[](text)[$symbol($version)]($style)[\]](text))'
style = "green"
symbol = " "

[c]
format = '([\[](text)[$symbol($version(-$name))]($style)[\]](text))'
style = "green"
symbol = " "

[character]
error_symbol = '[\$](bold red)'
success_symbol = '[\$](bold green)'
vimcmd_symbol = '[\$](bold green)'

[cmake]
format = '([\[](text)[$symbol($version)]($style)[\]](text))'
style = "green"
symbol = " "

[cmd_duration]
format = '([\[](text)[ $duration]($style)[\]─](text))'
min_time = 60_000
style = 'red'

[cobol]
format = '([\[](text)[$symbol($version)]($style)[\]](text))'
symbol = " "

[conda]
format = '([─\[](text)[$symbol$environment]($style)[\]](text))'
style = "green"
symbol = "󱔎 "

[container]
symbol = "⬢ "

[cpp]
disabled = false
format = '([\[](text)[$symbol($version(-$name))]($style)[\]](text))'
style = "green"
symbol = " "

[crystal]
format = '([\[](text)[$symbol($version)]($style)[\]](text))'
symbol = " "

[daml]
format = '([\[](text)[$symbol($version)]($style)[\]](text))'
symbol = "Λ "

[dart]
format = '([\[](text)[$symbol($version)]($style)[\]](text))'
symbol = " "

[deno]
format = '([\[](text)[$symbol($version)]($style)[\]](text))'
style = "green"
symbol = " "

[directory]
format = '[\[](text)([$read_only]($read_only_style))[$path]($style)[\]](text)'
read_only = "󰌾 "
style = "peach"
truncation_length = 10

[direnv]
disabled = false
format = '([─\[](text)[$loaded]($style)[\]](text))'
loaded_msg = ""
style = "blue"
symbol = ""
unloaded_msg = ""

[docker_context]
format = '([\[](text)[$symbol$context]($style)[\]](text))'
symbol = " "

[dotnet]
format = '([\[](text)[$symbol($version)(-$tfm)]($style)[\]](text))'
style = "green"
symbol = " "

[elixir]
format = '([\[](text)[$symbol($version \(OTP $otp_version\))]($style)[\]](text))'
symbol = " "

[elm]
format = '([\[](text)[$symbol($version)]($style)[\]](text))'
symbol = " "

[erlang]
format = '([\[](text)[$symbol($version)]($style)[\]](text))'
symbol = " "

[fennel]
format = '([\[](text)[$symbol($version)]($style)[\]](text))'
symbol = " "

[fill]
style = "text"
symbol = "─"

[fossil_branch]
format = '([\[](text)[$symbol$branch]($style)[\]](text))'
symbol = " "

[fossil_metrics]
disabled = true

[gcloud]
format = '([\[](text)[$symbol$account(@$domain)(\($region\))]($style)[\]](text))'
symbol = "󱇶 "

[git_branch]
format = '([\[](text)[$symbol$branch]($style)[\]](text))'
style = "yellow"
symbol = " "

[git_commit]
format = '([\[](text)[$hash$tag]($style)[\]](text))'
style = "yellow"
tag_symbol = "  "

[git_metrics]
disabled = true

[git_state]

[git_status]
format = '([\[](text)[$all_status$ahead_behind]($style)[\]](text))'
style = "yellow"

[gleam]
symbol = "󰦥 "

[golang]
format = '([\[](text)[$symbol($version)]($style)[\]](text))'
symbol = " "

[gradle]
format = '([\[](text)[$symbol($version)]($style)[\]](text))'
style = "green"
symbol = " "

[guix_shell]
format = '([\[](text)[$symbol]($style)[\]](text))'
symbol = ""

[haskell]
format = '([\[](text)[$symbol($version)]($style)[\]](text))'
style = "green"
symbol = " "

[hg_branch]
format = '([\[](text)[$symbol$branch]($style)[\]](text))'
symbol = " "

[haxe]
format = '([\[](text)[$symbol($version)]($style)[\]](text))'
symbol = " "

[helm]
format = '([\[](text)[$symbol($version)]($style)[\]](text))'
symbol = " "

[hostname]
format = "[$hostname$ssh_symbol]($style)"
ssh_only = false
ssh_symbol = " "
style = "lavender"

[java]
format = '([\[](text)[$symbol($version)]($style)[\]](text))'
style = "green"
symbol = " "

[jobs]
symbol = "✦ "

[julia]
format = '([\[](text)[$symbol($version)]($style)[\]](text))'
symbol = " "

[kotlin]
format = '([\[](text)[$symbol($version)]($style)[\]](text))'
symbol = " "

[kubernetes]
format = '([\[](text)[$symbol$context( \($namespace\))]($style)[\]](text))'
symbol = " "

[lua]
format = '([\[](text)[$symbol($version)]($style)[\]](text))'
style = "green"
symbol = " "

[memory_usage]
format = '([\[](text)$symbol[$ram( | $swap)]($style)[\]](text))'
symbol = "󰍛 "

[meson]
format = '([\[](text)[$symbol$project]($style)[\]](text))'
symbol = "󰔷 "

[mojo]
symbol = "󰈸 "

[nats]
symbol = " "

[netns]
symbol = "󰛳 "

[nim]
format = '([\[](text)[$symbol($version)]($style)[\]](text))'
symbol = "󰆥 "

[nix_shell]
format = '([─\[](text)[$symbol$state( \($name\))]($style)[\]](text))'
style = "blue"
symbol = " "

[nodejs]
format = '([\[](text)[$symbol($version)]($style)[\]](text))'
style = "green"
symbol = "󰎙 "

[ocaml]
format = '([\[](text)[$symbol($version)(\($switch_indicator$switch_name\))]($style)[\]](text))'
symbol = " "

[odin]
symbol = "󱢇 "

[opa]
format = '([\[](text)[$symbol($version)]($style)[\]](text))'
symbol = "󰗌 "

[openstack]
format = '([\[](text)[$symbol$cloud(\($project\))]($style)[\]](text))'
symbol = " "

[os]
disabled = false
format = '[\[](text)[$symbol]($style)[\]](text)'
style = 'red'

[os.symbols]
AlmaLinux = ""
Alpaquita = ""
Alpine = ""
Amazon = ""
Android = ""
Arch = ""
Artix = ""
CachyOS = ""
CentOS = ""
Debian = ""
DragonFly = ""
Emscripten = ""
EndeavourOS = ""
Fedora = ""
FreeBSD = ""
Garuda = "󰛓"
Gentoo = ""
HardenedBSD = "󰞌"
Illumos = "󰈸"
Kali = ""
Linux = ""
Mabox = ""
Macos = ""
Manjaro = ""
Mariner = ""
MidnightBSD = ""
Mint = ""
NetBSD = ""
NixOS = ""
Nobara = ""
OpenBSD = "󰈺"
OracleLinux = "󰌷"
Pop = ""
Raspbian = ""
RedHatEnterprise = ""
Redhat = ""
Redox = "󰀘"
RockyLinux = ""
SUSE = ""
Solus = "󰠳"
Ubuntu = ""
Unknown = ""
Void = ""
Windows = "󰍲"
openSUSE = ""

[package]
format = '([\[](text)[$symbol$version]($style)[\]](text))'
symbol = "󰏗 "

[perl]
format = '([\[](text)[$symbol($version)]($style)[\]](text))'
symbol = " "

[php]
format = '([\[](text)[$symbol($version)]($style)[\]](text))'
symbol = " "

[pijul_channel]
format = '([\[](text)[$symbol$channel]($style)[\]](text))'
symbol = " "

[pixi]
format = '([\[](text)[$symbol$version( $environment)]($style)[\]](text))'
symbol = "󰏗 "

[pulumi]
format = '([\[](text)[$symbol$stack]($style)[\]](text))'
symbol = " "

[purescript]
format = '([\[](text)[$symbol($version)]($style)[\]](text))'
symbol = " "

[python]
format = '([\[](text)[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))]($style)[\]](text))'
style = "green"
symbol = " "

[quarto]
symbol = "󰐗 "

[raku]
format = '([\[](text)[$symbol($version-$vm_version)]($style)[\]](text))'
symbol = "󱖉 "

[red]
format = '([\[](text)[$symbol($version)]($style)[\]](text))'
symbol = " "

[rlang]
symbol = " "

[ruby]
format = '([\[](text)[$symbol($version)]($style)[\]](text))'
symbol = " "

[rust]
format = '([─\[](text)[$symbol($version)]($style)[\]](text))'
style = "green"
symbol = "󱘗 "

[scala]
symbol = " "
format = '([\[](text)[$symbol($version)]($style)[\]](text))'

[shell]

[shlvl]

[singularity]
symbol = " "

[solidity]
format = '([\[](text)[$symbol($version)]($style)[\]](text))'
symbol = " "

[spack]
format = '([\[](text)[$symbol$environment]($style)[\]](text))'
symbol = " "

[status]

[sudo]
format = '([\[](text)[as $symbol]($style)[\]](text))'
symbol = "󱅞 "

[swift]
format = '([\[](text)[$symbol($version)]($style)[\]](text))'
symbol = " "

[terraform]
format = '([\[](text)[$symbol$workspace]($style)[\]](text))'
symbol = "󱁢 "

[time]
disabled = false
format = '[\[](text)[$time]($style)[\]](text)'
style = "mauve"

[typst]
symbol = " "

[username]
format = '[$user]($style)'
show_always = true
style_root = 'lavender'
style_user = 'lavender'

[vagrant]
format = '([\[](text)[$symbol($version)]($style)[\]](text))'
symbol = " "

[vcsh]
symbol = " "

[vlang]
format = '([\[](text)[$symbol($version)]($style)[\]](text))'
symbol = " "

[zig]
format = '([\[](text)[$symbol($version)]($style)[\]](text))'
symbol = " "

[palettes.tokyonight_night]
rosewater = "#ff899d"
flamingo = "#ff007c"
pink = "#bb9af7"
mauve = "#9d7cd8"
red = "#f7768e"
maroon = "#db4b4b"
peach = "#ff9e64"
yellow = "#e0af68"
green = "#9ece6a"
teal = "#73daca"
sky = "#7dcfff"
sapphire = "#2ac3de"
blue = "#7aa2f7"
lavender = "#c7a9ff"
text = "#c0caf5"
subtext1 = "#a9b1d6"
subtext0 = "#9aa5ce"
overlay2 = "#737aa2"
overlay1 = "#565f89"
overlay0 = "#3b4261"
surface2 = "#414868"
surface1 = "#292e42"
surface0 = "#16161e"
base = "#1a1b26"
mantle = "#16161e"
crust = "#0c0e14"

[palettes.catppuccin_macchiato]
rosewater = "#f4dbd6"
flamingo = "#f0c6c6"
pink = "#f5bde6"
red = "#ed8796"
maroon = "#ee99a0"
peach = "#f5a97f"
yellow = "#eed49f"
green = "#a6da95"
teal = "#8bd5ca"
sky = "#91d7e3"
sapphire = "#7dc4e4"
blue = "#8aadf4"
lavender = "#b7bdf8"
mauve = "#c6a0f6"
text = "#cad3f5"
subtext1 = "#b8c0e0"
subtext0 = "#a5adcb"
overlay2 = "#939ab7"
overlay1 = "#8087a2"
overlay0 = "#6e738d"
surface2 = "#5b6078"
surface1 = "#494d64"
surface0 = "#363a4f"
base = "#24273a"
mantle = "#1e2030"
crust = "#181926"
